# Generated by Django 3.2.9 on 2021-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=512)),
                ('row_size', models.IntegerField()),
                ('column_size', models.IntegerField()),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
