# Generated by Django 3.2.9 on 2021-11-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='column_size',
        ),
        migrations.RemoveField(
            model_name='project',
            name='row_size',
        ),
    ]
