# Generated by Django 3.2.9 on 2021-11-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20211116_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github',
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
