# Generated by Django 3.2.9 on 2021-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('authority', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=512)),
                ('download_link', models.CharField(max_length=512)),
            ],
        ),
    ]
